name: frontend-deploy
on:
  push:
    branches:
      - master
      - main
    paths:
      - 'cloud/frontend/xlab-cloud-workshop-chatbot/**' # Only deploy when changes are made to frontend

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/xlab-ws-chat-front:prod # change to prod if in production
  CONTAINER_NAME: xlab-ws-chat-front-server
jobs:
  publish:
    name: publish frontend image
    runs-on: ubuntu-latest
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}
      - id: updateenv
        run: echo "IMAGE_NAME=${{ steps.string.outputs.lowercase }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Login to ghcr
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build and Publish
        run: |
          cd cloud/frontend/xlab-cloud-workshop-chatbot
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  deploy:
    needs: publish
    name: deploy frontend image
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: install ssh keys
        # check this thread to understand why its needed:
        # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin && cd ${{ secrets.WORK_DIR }} && docker stop ${{ env.CONTAINER_NAME }} || true | xargs docker rm || true && docker compose pull ${{ env.CONTAINER_NAME }} && docker compose up -d ${{ env.CONTAINER_NAME }} && exit"
      - name: clean env
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && rm -f ${{ env.SEC_FILE_NAME }} && exit"
      - name: get time
        run: echo "TIME=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      - name: cleanup
        run: rm -rf ~/.ssh
